### ISSUE TITLE
requirements for testing

### ISSUE THREAD

**Issue by tyoungNIO** [niolabs/nio-cli#74]
running unit tests for nio-cli requires the python module `responses` which is not listed anywhere as a requirement:
```
c:\Users\Tom\nio\nio-cli>nose2
.E
======================================================================
ERROR: tests.test_cli (nose2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_cli
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nose2\plugins\loader\discovery.py", l
ine 201, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nose2\util.py", line 77, in module_fr
om_name
    __import__(name)
  File "c:\Users\Tom\nio\nio-cli\tests\test_cli.py", line 1, in <module>
    import responses
ModuleNotFoundError: No module named 'responses'


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)
```

**Comment by tlugger** [comment]
It looks like `responses` is listed as a requirement in the `setup.py` file. If you install this with `python3 setup.py test` you'll get the correct dependencies for running tests:

```
Searching for responses
Reading https://pypi.python.org/simple/responses/
Downloading https://pypi.python.org/packages/0c/5e/6c995768c35c622651aeb83c227dfc88c15fa42483a2d2a9ead705ff018a/responses-0.8.1-py2.py3-none-any.whl#md5=55bd291d10f561741c9a4f4f8071aef1
Best match: responses 0.8.1
Processing responses-0.8.1-py2.py3-none-any.whl
Installing responses-0.8.1-py2.py3-none-any.whl to /Users/tlugger/workspace/nio-cli/.eggs
writing requirements to /Users/tlugger/workspace/nio-cli/.eggs/responses-0.8.1-py3.6.egg/EGG-INFO/requires.txt
```

**Comment by tyoungNIO** [comment]
If you install with `python setup.py develop`, which is synonymous with `pip install -e`, you do not get responses package.

**Comment by tyoungNIO** [comment]
https://github.com/pypa/setuptools/issues/420

**Comment by tyoungNIO** [comment]
https://stackoverflow.com/questions/28509965/setuptools-development-requirements
