### ISSUE TITLE
newblock command is not windows compatible

### ISSUE THREAD

**Issue by tyoungNIO** [niolabs/nio-cli#83]
```c:\Users\Tom\nio>nio newblock image_classification
Cloning into 'image_classification'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 5 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), done.
'mv' is not recognized as an internal or external command,
operable program or batch file.
'mv' is not recognized as an internal or external command,
operable program or batch file.
'mv' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "c:\users\tom\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tom\AppData\Local\Programs\Python\Python36\Scripts\nio.exe\__main__.py", line 9, in <module>
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nio_cli\cli.py", line 59, in main
    command(options).run()
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nio_cli\commands\newblock.py", line 3
6, in run
    self.rename_block_class(self._block)
  File "c:\users\tom\appdata\local\programs\python\python36\lib\site-packages\nio_cli\commands\newblock.py", line 4
5, in rename_block_class
    with open('./{0}/{0}_block.py'.format(block)) as f:
FileNotFoundError: [Errno 2] No such file or directory: './image_classification/image_classification_block.py'```

**Comment by tyoungNIO** [comment]
Fixed in #107
