### ISSUE TITLE
creating a nio service with pip 10 fails

### ISSUE THREAD

**Issue by deliciousmonster** [niolabs/nio-cli#92]
Cloning into '/Users/jrepp/nio/projects/webserver/service_tests/modules/module_persistence_file'...
Submodule path 'service_tests/modules/module_persistence_file': checked out 'cfd854297df0599bdc30dbb41e55effc7e96dc94'
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/3.6/bin/nio", line 11, in <module>
   sys.exit(main())
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nio_cli/cli.py", line 59, in main
   command(options).run()
 File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nio_cli/commands/new.py", line 42, in run
   pip.main(['install', '-r', reqs])
AttributeError: module 'pip' has no attribute 'main'

-------------

https://stackoverflow.com/questions/49839610/attributeerror-module-pip-has-no-attribute-main (edited)

**Comment by mattdodge** [comment]
Fixed by #94 (I thought that was supposed to auto close it... 🤷‍♂️ )
